# Generated by Django 4.2.3 on 2023-08-01 05:26

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pac_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('pac_status', models.BooleanField(blank=True, choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, null=True)),
                ('register_date', models.DateField(default=datetime.date.today)),
                ('pac_number', models.IntegerField(unique=True)),
                ('pac_name', models.CharField(max_length=100)),
                ('pac_surename', models.CharField(max_length=100)),
                ('pac_dni', models.IntegerField(unique=True)),
                ('pac_birthdate', models.DateField()),
                ('pac_phone', models.IntegerField()),
                ('pac_address', models.CharField(max_length=100)),
                ('pac_email', models.EmailField(blank=True, max_length=100)),
                ('pac_education', models.CharField(max_length=100)),
                ('pac_workplace', models.CharField(max_length=100)),
                ('pac_other_act', models.CharField(max_length=255)),
                ('pac_times', models.CharField(max_length=255)),
                ('pac_civil_status', models.CharField(max_length=100)),
                ('pac_emot_bond', models.CharField(max_length=100)),
                ('pac_reason', models.TextField(max_length=255)),
                ('pac_other_treatment', models.CharField(max_length=100)),
                ('pac_pharmacology', models.CharField(max_length=255)),
                ('pac_referal_for', models.CharField(max_length=50)),
                ('pac_condition_history', models.CharField(max_length=50)),
                ('pac_other', models.TextField(max_length=255)),
            ],
            managers=[
                ('patients', django.db.models.manager.Manager()),
            ],
        ),
    ]
