# Generated by Django 4.2.3 on 2023-08-09 04:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('treatment_status', models.CharField(choices=[('Activo', 'activo'), ('Interrumpido', 'interrumpido'), ('Abandonado', 'abandonado'), ('Alta', 'alta')], default='activo', max_length=50, null=True, verbose_name='Tratamiento')),
                ('register_date', models.DateField(default=datetime.date.today, verbose_name='Registrado el')),
                ('pac_number', models.IntegerField(unique=True, verbose_name='Nº Hist. Clínica')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('birthdate', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('phone_number', models.IntegerField(blank=True, verbose_name='Telefono')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='E-mail')),
                ('education', models.CharField(blank=True, max_length=100, verbose_name='Estudios')),
                ('workplace', models.CharField(blank=True, max_length=100, verbose_name='Ocupación')),
                ('other_act', models.CharField(blank=True, max_length=255, verbose_name='Otras actividades')),
                ('times', models.CharField(blank=True, max_length=255, verbose_name='Tiempos')),
                ('civil_status', models.CharField(blank=True, choices=[('Soltero/a', 'Soltero'), ('Casado/a', 'Casado'), ('Divorciado/a', 'Divorciado'), ('Viudo/a', 'Viudo'), ('Separado/a', 'Separado'), ('En pareja', 'En pareja')], default='', max_length=100, verbose_name='Estado Civil')),
                ('afiliate_number', models.IntegerField(blank=True, null=True, verbose_name='Nº Afiliado')),
                ('cuil', models.IntegerField(blank=True, null=True, unique=True, verbose_name='CUIL')),
                ('reason', models.TextField(max_length=255, verbose_name='Motivo de consulta')),
                ('other_treatment', models.CharField(blank=True, max_length=100, verbose_name='Otros tratamientos')),
                ('pharmacology', models.CharField(blank=True, max_length=255, verbose_name='Medicación')),
                ('referal_for', models.CharField(blank=True, max_length=50, verbose_name='Referido por')),
                ('condition_history', models.CharField(blank=True, max_length=50, verbose_name='Historia del padecimiento')),
                ('other_info', models.TextField(blank=True, max_length=255, verbose_name='Otra información')),
            ],
            options={
                'ordering': ('pac_number',),
            },
        ),
        migrations.CreateModel(
            name='SocialSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Obra Social')),
                ('code_type', models.CharField(blank=True, choices=[('Nacional', 'nacional'), ('Provincial', 'provincial')], default='', max_length=100, null=True, verbose_name='Tipo de Nomenclador')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='PatientLogs',
            fields=[
                ('date_log', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('id_session', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Sesión')),
                ('session_log', models.TextField(max_length=255, verbose_name='Registro')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='clinic_history.patient', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Apellido')),
                ('relation', models.CharField(choices=[('Tutor/a', 'Tutor'), ('Progenitor/a', 'Progenitor'), ('Abuelo/a', 'Abuelo'), ('Amigo/a', 'Amigo'), ('Pareja', 'Pareja'), ('Hijo/a', 'Hijo'), ('Tio/a', 'Tio'), ('Conviviente', 'Conviviente'), ('Compañero/a', 'Compañero'), ('Otro', 'Otro')], default='', max_length=20, verbose_name='Relación')),
                ('phone_number', models.IntegerField(verbose_name='Contacto')),
                ('address', models.CharField(blank=True, max_length=20, verbose_name='Dirección')),
                ('other_info', models.TextField(blank=True, max_length=255, verbose_name='Info')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo_paciente', to='clinic_history.patient')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='ooss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic_history.socialsecurity', verbose_name='O.S'),
        ),
    ]
