# Generated by Django 4.2.3 on 2023-08-01 14:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('treatment_status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, null=True, verbose_name='Estado del tratamiento')),
                ('register_date', models.DateField(default=datetime.date.today)),
                ('pac_number', models.IntegerField(unique=True, verbose_name='Historia Clinica Nº')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('birthdate', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('phone_number', models.IntegerField(blank=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('workplace', models.CharField(blank=True, max_length=100)),
                ('other_act', models.CharField(blank=True, max_length=255)),
                ('times', models.CharField(blank=True, max_length=255)),
                ('civil_status', models.CharField(blank=True, max_length=100)),
                ('emotional_bond', models.CharField(blank=True, max_length=100)),
                ('ooss', models.CharField(blank=True, choices=[('ospe', 'OSPE'), ('particular', 'Particular')], default='', max_length=32, null=True)),
                ('cuil', models.IntegerField(blank=True, unique=True, verbose_name='CUIL')),
                ('reason', models.TextField(max_length=255)),
                ('other_treatment', models.CharField(blank=True, max_length=100)),
                ('pharmacology', models.CharField(blank=True, max_length=255)),
                ('referal_for', models.CharField(blank=True, max_length=50)),
                ('condition_history', models.CharField(blank=True, max_length=50)),
                ('other_info', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-id',),
            },
            managers=[
                ('patients', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Apellido')),
                ('relation', models.CharField(choices=[('tutor', 'Tutor/a'), ('parent', 'Progenitor/a'), ('grand', 'Abuelo/a'), ('friend', 'Amigo/a'), ('couple', 'Pareja'), ('children', 'Hijo/a'), ('uncle', 'Tio/a'), ('cohabitant', 'Conviviente'), ('mate', 'Compañero/a'), ('other', 'Otro')], default='', max_length=20, verbose_name='Relación')),
                ('phone_number', models.IntegerField(verbose_name='Contacto')),
                ('address', models.CharField(blank=True, max_length=20, verbose_name='Dirección')),
                ('other_info', models.TextField(blank=True, max_length=255, verbose_name='Info')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='clinic_history.patient')),
            ],
        ),
    ]
