# Generated by Django 4.2.3 on 2023-08-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('-name',)},
        ),
        migrations.AlterModelOptions(
            name='patientcontact',
            options={'ordering': ('-name',)},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emotional_bond',
        ),
        migrations.AlterField(
            model_name='patient',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Soltero/a'), ('married', 'Casado/a'), ('divorced', 'Divorciado/a'), ('widower', 'Viudo/a'), ('separated', 'Separado/a'), ('in_couple', 'En pareja')], default='', max_length=100),
        ),
    ]
