# Generated by Django 4.2.3 on 2023-08-01 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='pac_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_birthdate',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_civil_status',
            new_name='civil_status',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_condition_history',
            new_name='condition_history',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_dni',
            new_name='dni',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_education',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_emot_bond',
            new_name='emotional_bond',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_other_act',
            new_name='other_act',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_other',
            new_name='other_info',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_other_treatment',
            new_name='other_treatment',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_pharmacology',
            new_name='pharmacology',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_reason',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_referal_for',
            new_name='referal_for',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_surename',
            new_name='surename',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_times',
            new_name='times',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_status',
            new_name='treatment_status',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pac_workplace',
            new_name='workplace',
        ),
    ]
