# Generated by Django 4.2.3 on 2023-08-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_history', '0002_rename_pac_address_patient_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='surename',
            new_name='surname',
        ),
    ]
