# Generated by Django 4.2.3 on 2023-08-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_history', '0002_alter_patient_options_alter_patientcontact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cuil',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='CUIL'),
        ),
    ]
