# Generated by Django 4.2.3 on 2023-08-02 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_history', '0003_alter_patient_cuil'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='patient',
            managers=[
            ],
        ),
    ]
