# Generated by Django 4.2.3 on 2023-08-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_history', '0003_alter_patientlogs_n_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlogs',
            name='id_session',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Sesión'),
        ),
        migrations.AlterField(
            model_name='patientlogs',
            name='session_log',
            field=models.TextField(max_length=1024, verbose_name='Registro'),
        ),
    ]
