# Generated by Django 4.2.3 on 2023-08-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_history', '0003_rename_surename_patient_surname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('-id',)},
        ),
    ]
