# Generated by Django 4.2.3 on 2023-08-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_history', '0004_alter_patient_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pac_number',
            field=models.IntegerField(unique=True, verbose_name='Nº Historia Clinica'),
        ),
    ]
