# Generated by Django 4.2.3 on 2023-09-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_history', '0004_alter_patientlogs_id_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlogs',
            name='session_log',
            field=models.TextField(max_length=5000, verbose_name='Registro'),
        ),
        migrations.AlterField(
            model_name='socialsecurity',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
