# Generated by Django 4.2.3 on 2023-09-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_history', '0005_alter_patientlogs_session_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsecurity',
            name='desc',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
    ]
