# Generated by Django 4.2.3 on 2023-08-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_history', '0005_alter_patient_pac_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ooss',
            field=models.CharField(blank=True, choices=[('ospe', 'OSPE'), ('Particular', 'particular')], default='', max_length=32, null=True),
        ),
    ]
