# Generated by Django 4.2.3 on 2023-08-03 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_history', '0006_alter_patient_ooss'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='afiliate_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº Afiliado'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Soltero/a'), ('married', 'Casado/a'), ('divorced', 'Divorciado/a'), ('widower', 'Viudo/a'), ('separated', 'Separado/a'), ('in_couple', 'En pareja')], default='', max_length=100, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='condition_history',
            field=models.CharField(blank=True, max_length=50, verbose_name='Historia del padecimiento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='education',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estudios'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ooss',
            field=models.CharField(blank=True, choices=[('ospe', 'OSPE'), ('particular', 'Particular')], default='', max_length=32, null=True, verbose_name='O.S'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='other_act',
            field=models.CharField(blank=True, max_length=255, verbose_name='Otras actividades'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='other_info',
            field=models.TextField(blank=True, max_length=255, verbose_name='Otra información'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='other_treatment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Otros tratamientos'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pac_number',
            field=models.IntegerField(unique=True, verbose_name='Nº Hist. Clínica'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pharmacology',
            field=models.CharField(blank=True, max_length=255, verbose_name='Medicación'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.IntegerField(blank=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reason',
            field=models.TextField(max_length=255, verbose_name='Motivo de consulta'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='referal_for',
            field=models.CharField(blank=True, max_length=50, verbose_name='Referido por: '),
        ),
        migrations.AlterField(
            model_name='patient',
            name='register_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Registrado el: '),
        ),
        migrations.AlterField(
            model_name='patient',
            name='times',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tiempos'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='treatment_status',
            field=models.CharField(choices=[('activo', 'Activo'), ('interrumpido', 'interrumpido'), ('abandonado', 'Abandonado'), ('alta', 'Alta')], default='activo', max_length=50, null=True, verbose_name='Tratamiento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='workplace',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ocupación'),
        ),
    ]
